# Generated by Django 4.2.4 on 2024-04-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
    ]
