# Generated by Django 4.2.4 on 2024-05-04 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('subject', models.TextField(max_length=50)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='category',
            field=models.CharField(default='men', max_length=10),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='image',
            field=models.ImageField(upload_to='djangouploads/files/covers'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField(default=1)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shopproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
