# Generated by Django 4.2.4 on 2024-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='category',
            field=models.CharField(default='men', max_length=10),
        ),
    ]
