# Generated by Django 4.2.4 on 2024-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shopproducts_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('subject', models.TextField(max_length=50)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='image',
            field=models.ImageField(upload_to='djangouploads/files/covers'),
        ),
    ]
